name: vibetune
description: A stylish music player with modern UI and animations
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.10.5
  audio_session: ^0.2.2
  on_audio_query: ^2.9.0
  provider: ^6.1.2
  google_fonts: ^6.2.1
  animations: ^2.0.8
  flutter_vector_icons: ^2.0.0
  permission_handler: ^12.0.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true